# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:

production:
  adapter: mysql
  database: privateprison_production
  username: root
  password: 
  host: 127.0.0.1

development:
  adapter: mysql
  database: privateprison_development
  username: root
  password: 
  host: 127.0.0.1

test: &TEST
  adapter: mysql
  database: privateprison_test
  username: root
  password: 
  host: 127.0.0.1
cucumber:
  <<: *TEST
