# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.

test: &TEST
  adapter: mysql
  database: privateprison_test
  username: pp_test
  password: pp_test
  host: sun115.dms.state.fl.us

cucumber:
  <<: *TEST
